defaults: &defaults
  docker:
    - image: circleci/golang:1.13
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go get -v -t -d ./...
  test:
    <<: *defaults
    steps:
      - checkout
      - run: go test -v ./...
